# This file created by conda-build 3.0.28
# meta.yaml template originally from:
# /Users/travis/build/quantopian/zipline/conda/zipline, last modified Tue Jul 17 00:41:04 2018
# ------------------------------------------------

package:
    name: zipline
    version: 1.3.0
source:
    git_url: /Users/travis/build/quantopian/zipline
build:
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: np114py35_0
requirements:
    build:
        - mkl 2018.0.3 1
        - xz 5.2.4 h1de35cc_4
        - intel-openmp 2018.0.3 0
        - python 3.5.5 h0a44026_3
        - openssl 1.0.2o h26aff7b_0
        - cython 0.25.2 py35_0
        - libedit 3.1.20170329 hb402a30_2
        - pip 10.0.1 py35_0
        - zlib 1.2.11 hf3cbc9b_2
        - libgfortran 3.0.1 h93005f0_2
        - blas 1.0 mkl
        - libcxx 4.0.1 h579ed51_0
        - numpy 1.14.5 py35h9bb19eb_0
        - ca-certificates 2018.03.07 0
        - mkl_random 1.0.1 py35h78cc56f_0
        - tk 8.6.7 h35a86e2_3
        - certifi 2018.4.16 py35_0
        - ncurses 6.1 h0a44026_0
        - sqlite 3.24.0 ha441bb4_0
        - wheel 0.31.1 py35_0
        - numpy-base 1.14.5 py35ha9ae307_0
        - libffi 3.2.1 h475c297_4
        - mkl_fft 1.0.1 py35h917ab60_0
        - libcxxabi 4.0.1 hebd6815_0
        - setuptools 39.2.0 py35_0
        - readline 7.0 hc1231fa_4
    run:
        - networkx >=1.9.1,<2.0
        - alembic >=0.7.7
        - bottleneck >=1.0.0
        - pandas >=0.18.1,<=0.22
        - python-dateutil >=2.4.2
        - python >=3.5,<3.6.0a0
        - pytables >=3.3.0
        - intervaltree >=2.1.0
        - decorator >=4.0.0
        - markupsafe >=0.23
        - contextlib2 >=0.4.0
        - pytz >=2016.4
        - pandas-datareader >=0.2.1
        - patsy >=0.4.0
        - toolz >=0.8.2
        - logbook >=0.12.5
        - requests >=2.9.1
        - numexpr >=2.6.1
        - cyordereddict >=0.2.2
        - cython >=0.25.2
        - requests-file >=1.4.1
        - empyrical >=0.5.0
        - sqlalchemy >=1.0.8
        - click >=4.0.0
        - scipy >=0.17.1
        - setuptools >18.0
        - lru-dict >=1.1.4
        - multipledispatch >=0.4.8
        - trading-calendars >=1.0.1
        - bcolz >=0.12.1,<1
        - mako >=1.0.1
        - six >=1.10.0
        - pip >=7.1.0
        - statsmodels >=0.6.1
        - numpy >=1.14,<1.15.0a0
        - sortedcontainers >=1.4.4
test:
    imports:
        - zipline
about:
    home: https://zipline.io
    license: Apache Software License
extra:
    copy_test_source_files: true
    final: true
